global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8000']

  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api_gateway:8080']

  - job_name: 'root_app'
    static_configs:
      - targets: ['tradesage_app:80']
