"""add_index_to_session_uuid

Revision ID: a39ec4a87ce0
Revises: 252bb18e8a30
Create Date: 2025-07-09 13:08:52.155329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39ec4a87ce0'
down_revision: Union[str, None] = '252bb18e8a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_session_uuid'), 'user_sessions', ['session_uuid'], unique=False, schema='shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_session_uuid'), table_name='user_sessions', schema='shared')
    # ### end Alembic commands ###
